version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ".:/usr/share/nginx/html"
  react:
    build: "./app"
    ports:
      - "3000:3000"
    volumes:
      - "./app/public:/app/public"
      - "./app/src:/app/src"
  storybook:
    build: "./app"
    command: bash -c "npm run storybook"
    ports:
      - "6006:6006"
    volumes:
      - "./app/public:/app/public"
      - "./app/src:/app/src"
      - "./app/.storybook:/app/.storybook"
  api:
    build: "./api"
    ports:
      - "3001:3001"
  vscode:
    build: "./vscode"
    ports:
      - "8000:8000"
    privileged: true
    command: bash -c "tail -f /dev/null"